name = "Information"
uuid = "27e68e20-e3af-48ea-a5d4-c7afd817b96e"
authors = ["kwatme <kwat.me@icloud.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Plot = "9db1e993-d40e-4a2c-9c84-e29bd56acb85"
